apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  # these labels belongs to deplyment resource
  labels:
    project: expense11
    component: mysql11
    environment: dev11
    tier: db11
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:
      project: expense
      component: mysql
      environment: dev
      tier: db
    # below is the pod defination
  template:
    metadata:
      labels:
        project: expense
        component: mysql
        environment: dev
        tier: db
    spec:
      containers:
      - name: mysql
        image: charan466/mysql:1.0.0
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 10
          periodSeconds: 5
        env:
            - name: MYSQL_ROOT_PASSWORD
              value: ExpenseApp@1

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    project: expense
    component: mysql
    environment: dev
    tier: db
  ports:
  - protocol: TCP
    port: 3306 #service-port
    targetPort: 3306 #target-port
